In [16]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

# DEPENDENT VARIABLE-"Pclass" , INDEPENDENT VARIABLE-"Survived,Sex,Age,SibSp,Parch,Fare,Embarked"

In [7]:
pwd

'C:\\Users\\HOME'

In [10]:
naive=pd.read_csv('train.csv')

In [13]:
new_age=np.where(naive['Age'].isnull(),28,naive['Age'])
naive['Age']=new_age

In [33]:
encoder=preprocessing.LabelEncoder()
naive['Sex']=encoder.fit_transform(v['Sex'])
naive['Embarked']=encoder.fit_transform(naive['Embarked'])

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
from sklearn.naive_bayes import*

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
from sklearn.metrics import confusion_matrix

In [48]:
y=naive['Pclass']
X=naive.drop(['Pclass','Name','Ticket','Cabin','PassengerId'],axis=1)

In [49]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [50]:
clf=BernoulliNB()

In [51]:
y_pred=clf.fit(X_train,y_train).predict(X_test)

In [52]:
accuracy_score(y_test,y_pred,normalize=True)

0.5917602996254682

In [53]:
confusion_matrix(y_test,y_pred) 

array([[ 30,   8,  32],
       [  9,  10,  30],
       [ 24,   6, 118]], dtype=int64)

# DEPENDENT VARIABLE-"Sex" , INDEPENDENT VARIABLE-"Survived,Pclass,Age,SibSp,Parch,Fare,Embarked"

In [54]:
naive.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [55]:
y=naive['Sex']
X=naive.drop(['Sex','Name','Ticket','Cabin','PassengerId'],axis=1)

In [56]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [57]:
y_pred=clf.fit(X_train,y_train).predict(X_test)

In [58]:
accuracy_score(y_test,y_pred,normalize=True)

0.7453183520599251

In [59]:
confusion_matrix(y_test,y_pred) 

array([[ 49,  49],
       [ 19, 150]], dtype=int64)

# DEPENDENT VARIABLE-"SibSp" , INDEPENDENT VARIABLE-"Survived,Pclass,Sex,Age,Parch,Fare,Embarked"

In [60]:
y=naive['SibSp']
X=naive.drop(['SibSp','Name','Ticket','Cabin','PassengerId'],axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
y_pred=clf.fit(X_train,y_train).predict(X_test)


In [61]:
accuracy_score(y_test,y_pred,normalize=True)

0.6891385767790262

In [62]:
confusion_matrix(y_test,y_pred) 

array([[162,  20,   0,   0,   0,   0,   0],
       [ 43,  22,   0,   0,   0,   0,   0],
       [  6,   2,   0,   0,   0,   0,   0],
       [  5,   2,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0]], dtype=int64)

# DEPENDENT VARIABLE-"Parch" , INDEPENDENT VARIABLE-"Survived,Pclass,Sex,Age,SibSp,Fare,Embarked"

In [63]:
y=naive['Parch']
X=naive.drop(['Parch','Name','Ticket','Cabin','PassengerId'],axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
y_pred=clf.fit(X_train,y_train).predict(X_test)


In [64]:
accuracy_score(y_test,y_pred,normalize=True)

0.7153558052434457

In [65]:
confusion_matrix(y_test,y_pred) 

array([[182,  16,   0,   0,   0],
       [ 31,   9,   0,   0,   0],
       [ 24,   3,   0,   0,   0],
       [  1,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0]], dtype=int64)

# DEPENDENT VARIABLE-"Embarked" , INDEPENDENT VARIABLE-"Survived,Pclass,Sex,Age,SibSp,Fare,Parch"

In [66]:
y=naive['Embarked']
X=naive.drop(['Embarked','Name','Ticket','Cabin','PassengerId'],axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
y_pred=clf.fit(X_train,y_train).predict(X_test)

In [67]:
accuracy_score(y_test,y_pred,normalize=True)

0.7340823970037453

In [68]:
confusion_matrix(y_test,y_pred)

array([[  0,   0,  49],
       [  0,   0,  22],
       [  0,   0, 196]], dtype=int64)