# 1. Create a 3x3x3 array with random values 

In [11]:
from numpy import *
a=random.rand(3,3,3)
a

array([[[0.57517948, 0.09195797, 0.54057438],
        [0.77458721, 0.55847923, 0.13939857],
        [0.08746794, 0.9329522 , 0.4202037 ]],

       [[0.28001917, 0.62967442, 0.58624879],
        [0.31278119, 0.32677733, 0.23987314],
        [0.26086031, 0.45319449, 0.45013412]],

       [[0.19034838, 0.03198435, 0.27840443],
        [0.93302954, 0.94995428, 0.10446325],
        [0.73496826, 0.94878772, 0.47450779]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [17]:
from numpy import *
a = ones((3,3))
print("Checkerboard pattern:")
a = zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [18]:
from numpy import *
x= random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print('Normalized array:')
print(x)

Original Array:
[[0.0385223  0.03170028 0.14614823 0.01201322 0.33706773]
 [0.74567719 0.2900439  0.88090634 0.25992272 0.51510499]
 [0.40337092 0.64420997 0.52644923 0.50017024 0.59075968]
 [0.6526344  0.60677866 0.96522442 0.36027057 0.73075581]
 [0.6053785  0.35469745 0.29136187 0.4668262  0.30203754]]
Normalized array:
[[0.02781029 0.02065341 0.14071909 0.         0.34100996]
 [0.76967619 0.29167794 0.91154312 0.26007825 0.52778625]
 [0.41056767 0.66322841 0.53968734 0.51211842 0.60715449]
 [0.67206636 0.62395977 1.         0.36535172 0.75402239]
 [0.62249088 0.35950504 0.2930606  0.47713768 0.30426029]]


# 5.  How to find common values between two arrays?

In [21]:
from numpy import *
array1 = array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [22]:
from numpy import *
yesterday = datetime64('today', 'D') - timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = datetime64('today', 'D')
print("Today: ",today)
tomorrow  = datetime64('today', 'D') + timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [23]:
a = array([[1,2],[3,4]])
b = array([[2,6],[3,4]])
c = a == b
equal_arrays = c. all()
print(equal_arrays)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [4]:
from numpy import *
a=random.random(10)
print(a)
a[a.argmax()]=0
a

[0.46122429 0.77544435 0.81691891 0.03220056 0.46483059 0.99003528
 0.07997813 0.39537432 0.92380386 0.86852176]


array([0.46122429, 0.77544435, 0.81691891, 0.03220056, 0.46483059,
       0.        , 0.07997813, 0.39537432, 0.92380386, 0.86852176])

# 9. How to print all the values of an array?

In [31]:
z=array([1,5,1,3,8,3])
for i in z:
    print(i)
    

1
5
1
3
8
3


# 10.Subtract the mean of each row of a matrix

In [24]:
print("Original matrix:\n")
X = random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.61292191 0.32044563 0.3614901  0.19617725 0.1089955  0.63711644
  0.90319797 0.8411757  0.02721607 0.6253156 ]
 [0.48803644 0.21326534 0.01594685 0.05784302 0.5026511  0.90649683
  0.84416938 0.91377124 0.76944337 0.30500888]
 [0.95621292 0.90277152 0.13076301 0.81586389 0.22502833 0.46002428
  0.85716202 0.05151071 0.80522547 0.90066523]
 [0.41978617 0.93858802 0.34671158 0.66661185 0.09042315 0.09663252
  0.24586468 0.84850295 0.44595294 0.55604458]
 [0.64526533 0.22586116 0.78542633 0.97861831 0.76799706 0.7545209
  0.92091031 0.00980777 0.52737723 0.9047054 ]]

Subtract the mean of each row of the said matrix:

[[ 0.1495167  -0.14295959 -0.10191512 -0.26722797 -0.35440972  0.17371123
   0.43979275  0.37777049 -0.43618915  0.16191038]
 [-0.01362681 -0.2883979  -0.4857164  -0.44382023  0.00098786  0.40483358
   0.34250614  0.412108    0.26778013 -0.19665436]
 [ 0.34569018  0.29224878 -0.47975973  0.20534115 -0.38549441 -0.15049846
   0.24663928 -0.55901203  0.19

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [25]:
from numpy import *
a=array([[1,6],[5,9]])
b=array([[20,13],[5,17]])
c=dot(a,b)
print('diagonal of a dot product:',c.diagonal())

diagonal of a dot product: [ 50 218]


# 13.How to find the most frequent value in an array?

In [26]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 5 5 2 9 0 0 6 5 1 9 7 3 2 0 4 5 2 9 9 2 1 8 4 1 1 7 3 4 6 6 5 2 9 5 6 0
 7 0 3]
Most frequent value in the above array:
2


# 14.How to get the n largest values of an array

In [9]:
# method-1
from numpy import *
a=array([10,6,8,5,9])
a.sort()
max=a[0]
for i in range(1,len(a)):
    if a[i]>max:
        max=a[i]
print(max) 

10


In [10]:
# method-2
from numpy import *
a=array([10,6,8,5,9])
a.sort()
print(a[len(a)-1])   

10


# 15.How to create a record array from a regular array?

In [30]:
array1 = np.array([("swift", 45, 99),
                 ("verna", 13, 91),
             ("triumph", 83, 13)])
print("Original arrays:")
print(array1)
result = np.core.records.fromarrays(array1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print("\nRecord array;")
print(result)

Original arrays:
[['swift' '45' '99']
 ['verna' '13' '91']
 ['triumph' '83' '13']]

Record array;
[(b'swift', 45., 99) (b'verna', 13., 91) (b'triumph', 83., 13)]
